import type { AdminDashboard, AdminListing, AdminUser } from "@/models/admin";

const dashboard: AdminDashboard = {
  metrics: [
    {
      helper: "Contas novas, perfis e documentos",
      id: "users",
      label: "Usuarios",
      tone: "blue",
      value: "1.248",
    },
    {
      helper: "Produtos, servicos, vagas e imoveis",
      id: "listings",
      label: "Anuncios ativos",
      tone: "green",
      value: "386",
    },
    {
      helper: "Compras, entregas e suporte",
      id: "orders",
      label: "Pedidos abertos",
      tone: "yellow",
      value: "42",
    },
    {
      helper: "Conteudo aguardando decisao",
      id: "moderation",
      label: "Moderacao",
      tone: "red",
      value: "17",
    },
  ],
  queue: [
    {
      age: "12 min",
      area: "Anuncios",
      id: "fila-produto-fone",
      owner: "Tech Center Sinop",
      priority: "alta",
      status: "Revisar imagens",
      title: "Smartphone preto 256 GB",
    },
    {
      age: "28 min",
      area: "Financeiro",
      id: "fila-saque-afiliado",
      owner: "Maria Oliveira",
      priority: "alta",
      status: "Validar saque",
      title: "Saque afiliado R$ 84,70",
    },
    {
      age: "1 h",
      area: "Eventos",
      id: "fila-evento-privado",
      owner: "Studio Thais Lemos",
      priority: "media",
      status: "Aprovar divulgacao",
      title: "Workshop privado de beleza",
    },
    {
      age: "3 h",
      area: "Suporte",
      id: "fila-pedido-entrega",
      owner: "Pedido #8391",
      priority: "baixa",
      status: "Aguardar retorno",
      title: "Entrega em rota atrasada",
    },
  ],
  roles: [
    { id: "super-admin", label: "Super admin", scope: "Acesso total e permissoes" },
    { id: "operador", label: "Operador", scope: "Usuarios, anuncios e pedidos" },
    { id: "financeiro", label: "Financeiro", scope: "Carteira, afiliados e saques" },
    { id: "moderador", label: "Moderador", scope: "Conteudo, eventos e suporte" },
    { id: "vendedor", label: "Vendedor", scope: "Loja, anuncios e pedidos proprios" },
  ],
  sections: [
    {
      href: "/admin/users",
      id: "users",
      label: "Usuarios",
      pending: 8,
      summary: "Cadastro, perfil, documentos e bloqueios",
    },
    {
      href: "/admin?view=categories",
      id: "categories",
      label: "Categorias",
      pending: 3,
      summary: "Arvore, icones, destaque e ordenacao",
    },
    {
      href: "/admin/listings",
      id: "listings",
      label: "Produtos e anuncios",
      pending: 17,
      summary: "Aprovacao, midias, preco e vendedor",
    },
    {
      href: "/admin?view=orders",
      id: "orders",
      label: "Pedidos",
      pending: 11,
      summary: "Pagamento, entrega, cancelamento e suporte",
    },
    {
      href: "/admin?view=finance",
      id: "finance",
      label: "Financeiro",
      pending: 5,
      summary: "Carteira, cashback, afiliados e saques",
    },
    {
      href: "/admin?view=moderation",
      id: "moderation",
      label: "Moderacao",
      pending: 17,
      summary: "Conteudo, eventos, denuncia e revisao",
    },
    {
      href: "/admin?view=support",
      id: "support",
      label: "Suporte",
      pending: 9,
      summary: "Tickets, pedidos, usuarios e SLA",
    },
    {
      href: "/admin?view=reports",
      id: "reports",
      label: "Relatorios",
      pending: 2,
      summary: "Vendas, crescimento, operacao e logs",
    },
  ],
};

const users: AdminUser[] = [
  {
    city: "Sinop - MT",
    createdAt: "29/05/2026",
    email: "maria.oliveira@suwave.local",
    id: "user-maria-oliveira",
    lastAccess: "Hoje, 08:42",
    name: "Maria Oliveira",
    orders: 8,
    phone: "(66) 99912-3488",
    role: "Afiliada",
    status: "review",
    statusLabel: "Revisar saque",
    verified: true,
  },
  {
    city: "Sinop - MT",
    createdAt: "28/05/2026",
    email: "joao.silva@suwave.local",
    id: "user-joao-silva",
    lastAccess: "Hoje, 07:15",
    name: "Joao Silva",
    orders: 3,
    phone: "(66) 99845-1122",
    role: "Vendedor",
    status: "active",
    statusLabel: "Ativo",
    verified: true,
  },
  {
    city: "Sorriso - MT",
    createdAt: "27/05/2026",
    email: "studio.thais@suwave.local",
    id: "user-studio-thais",
    lastAccess: "Ontem, 18:09",
    name: "Studio Thais Lemos",
    orders: 14,
    phone: "(66) 99622-9090",
    role: "Empresa",
    status: "active",
    statusLabel: "Ativo",
    verified: true,
  },
  {
    city: "Sinop - MT",
    createdAt: "26/05/2026",
    email: "conta.pendente@suwave.local",
    id: "user-conta-pendente",
    lastAccess: "26/05/2026",
    name: "Conta Pendente",
    orders: 0,
    phone: "(66) 99000-1100",
    role: "Comprador",
    status: "review",
    statusLabel: "Perfil incompleto",
    verified: false,
  },
  {
    city: "Lucas do Rio Verde - MT",
    createdAt: "24/05/2026",
    email: "bloqueio.teste@suwave.local",
    id: "user-bloqueio-teste",
    lastAccess: "25/05/2026",
    name: "Bloqueio Teste",
    orders: 1,
    phone: "(66) 99123-0000",
    role: "Vendedor",
    status: "blocked",
    statusLabel: "Bloqueado",
    verified: false,
  },
];

const listings: AdminListing[] = [
  {
    city: "Sinop - MT",
    createdAt: "29/05/2026",
    id: "admin-listing-ranger",
    mediaCount: 5,
    price: "R$ 179.900,00",
    seller: "Auto Center Silva",
    status: "published",
    statusLabel: "Publicado",
    title: "Ford Ranger XLT 3.2 4x4",
    type: "Veiculo",
    updatedAt: "Hoje, 08:55",
  },
  {
    city: "Sinop - MT",
    createdAt: "29/05/2026",
    id: "admin-listing-fone",
    mediaCount: 2,
    price: "R$ 3.499,00",
    seller: "Tech Center Sinop",
    status: "review",
    statusLabel: "Revisar midias",
    title: "Smartphone preto 256 GB",
    type: "Produto",
    updatedAt: "Hoje, 08:12",
  },
  {
    city: "Sinop - MT",
    createdAt: "28/05/2026",
    id: "admin-listing-pizza",
    mediaCount: 3,
    price: "R$ 49,90",
    seller: "Hamburgueria Salamanca Ca'dore",
    status: "published",
    statusLabel: "Publicado",
    title: "Pizza grande com entrega",
    type: "Comida",
    updatedAt: "Ontem, 19:30",
  },
  {
    city: "Sorriso - MT",
    createdAt: "27/05/2026",
    id: "admin-listing-beauty",
    mediaCount: 4,
    price: "A partir de R$ 80,00",
    seller: "Studio Thais Lemos",
    status: "review",
    statusLabel: "Aprovar servico",
    title: "Pacote de escova e hidratacao",
    type: "Servico",
    updatedAt: "Ontem, 17:05",
  },
  {
    city: "Sinop - MT",
    createdAt: "26/05/2026",
    id: "admin-listing-house",
    mediaCount: 6,
    price: "R$ 750.000,00",
    seller: "Oliveira Imoveis",
    status: "paused",
    statusLabel: "Pausado",
    title: "Casa a venda - Jardim das Oliveiras",
    type: "Imovel",
    updatedAt: "26/05/2026",
  },
  {
    city: "Lucas do Rio Verde - MT",
    createdAt: "25/05/2026",
    id: "admin-listing-rejected",
    mediaCount: 1,
    price: "R$ 120,00",
    seller: "Conta Bloqueada",
    status: "rejected",
    statusLabel: "Rejeitado",
    title: "Anuncio sem descricao suficiente",
    type: "Produto",
    updatedAt: "25/05/2026",
  },
];

export function getAdminDashboard() {
  return dashboard;
}

export function getAdminUsers() {
  return users;
}

export function getAdminListings() {
  return listings;
}
