import type {
  AdminCategory,
  AdminDashboard,
  AdminFinanceItem,
  AdminListing,
  AdminModerationItem,
  AdminOrder,
  AdminUser,
} from "@/models/admin";

const dashboard: AdminDashboard = {
  metrics: [
    {
      helper: "Contas novas, perfis e documentos",
      id: "users",
      label: "Usuarios",
      tone: "blue",
      value: "1.248",
    },
    {
      helper: "Produtos, servicos, vagas e imoveis",
      id: "listings",
      label: "Anuncios ativos",
      tone: "green",
      value: "386",
    },
    {
      helper: "Compras, entregas e suporte",
      id: "orders",
      label: "Pedidos abertos",
      tone: "yellow",
      value: "42",
    },
    {
      helper: "Conteudo aguardando decisao",
      id: "moderation",
      label: "Moderacao",
      tone: "red",
      value: "17",
    },
  ],
  queue: [
    {
      age: "12 min",
      area: "Anuncios",
      id: "fila-produto-fone",
      owner: "Tech Center Sinop",
      priority: "alta",
      status: "Revisar imagens",
      title: "Smartphone preto 256 GB",
    },
    {
      age: "28 min",
      area: "Financeiro",
      id: "fila-saque-afiliado",
      owner: "Maria Oliveira",
      priority: "alta",
      status: "Validar saque",
      title: "Saque afiliado R$ 84,70",
    },
    {
      age: "1 h",
      area: "Eventos",
      id: "fila-evento-privado",
      owner: "Studio Thais Lemos",
      priority: "media",
      status: "Aprovar divulgacao",
      title: "Workshop privado de beleza",
    },
    {
      age: "3 h",
      area: "Suporte",
      id: "fila-pedido-entrega",
      owner: "Pedido #8391",
      priority: "baixa",
      status: "Aguardar retorno",
      title: "Entrega em rota atrasada",
    },
  ],
  roles: [
    { id: "super-admin", label: "Super admin", scope: "Acesso total e permissoes" },
    { id: "operador", label: "Operador", scope: "Usuarios, anuncios e pedidos" },
    { id: "financeiro", label: "Financeiro", scope: "Carteira, afiliados e saques" },
    { id: "moderador", label: "Moderador", scope: "Conteudo, eventos e suporte" },
    { id: "vendedor", label: "Vendedor", scope: "Loja, anuncios e pedidos proprios" },
  ],
  sections: [
    {
      href: "/admin/users",
      id: "users",
      label: "Usuarios",
      pending: 8,
      summary: "Cadastro, perfil, documentos e bloqueios",
    },
    {
      href: "/admin/categories",
      id: "categories",
      label: "Categorias",
      pending: 3,
      summary: "Arvore, icones, destaque e ordenacao",
    },
    {
      href: "/admin/listings",
      id: "listings",
      label: "Produtos e anuncios",
      pending: 17,
      summary: "Aprovacao, midias, preco e vendedor",
    },
    {
      href: "/admin/orders",
      id: "orders",
      label: "Pedidos",
      pending: 11,
      summary: "Pagamento, entrega, cancelamento e suporte",
    },
    {
      href: "/admin/finance",
      id: "finance",
      label: "Financeiro",
      pending: 5,
      summary: "Carteira, cashback, afiliados e saques",
    },
    {
      href: "/admin/moderation",
      id: "moderation",
      label: "Moderacao",
      pending: 17,
      summary: "Conteudo, eventos, denuncia e revisao",
    },
    {
      href: "/admin?view=support",
      id: "support",
      label: "Suporte",
      pending: 9,
      summary: "Tickets, pedidos, usuarios e SLA",
    },
    {
      href: "/admin?view=reports",
      id: "reports",
      label: "Relatorios",
      pending: 2,
      summary: "Vendas, crescimento, operacao e logs",
    },
  ],
};

const users: AdminUser[] = [
  {
    city: "Sinop - MT",
    createdAt: "29/05/2026",
    email: "maria.oliveira@suwave.local",
    id: "user-maria-oliveira",
    lastAccess: "Hoje, 08:42",
    name: "Maria Oliveira",
    orders: 8,
    phone: "(66) 99912-3488",
    role: "Afiliada",
    status: "review",
    statusLabel: "Revisar saque",
    verified: true,
  },
  {
    city: "Sinop - MT",
    createdAt: "28/05/2026",
    email: "joao.silva@suwave.local",
    id: "user-joao-silva",
    lastAccess: "Hoje, 07:15",
    name: "Joao Silva",
    orders: 3,
    phone: "(66) 99845-1122",
    role: "Vendedor",
    status: "active",
    statusLabel: "Ativo",
    verified: true,
  },
  {
    city: "Sorriso - MT",
    createdAt: "27/05/2026",
    email: "studio.thais@suwave.local",
    id: "user-studio-thais",
    lastAccess: "Ontem, 18:09",
    name: "Studio Thais Lemos",
    orders: 14,
    phone: "(66) 99622-9090",
    role: "Empresa",
    status: "active",
    statusLabel: "Ativo",
    verified: true,
  },
  {
    city: "Sinop - MT",
    createdAt: "26/05/2026",
    email: "conta.pendente@suwave.local",
    id: "user-conta-pendente",
    lastAccess: "26/05/2026",
    name: "Conta Pendente",
    orders: 0,
    phone: "(66) 99000-1100",
    role: "Comprador",
    status: "review",
    statusLabel: "Perfil incompleto",
    verified: false,
  },
  {
    city: "Lucas do Rio Verde - MT",
    createdAt: "24/05/2026",
    email: "bloqueio.teste@suwave.local",
    id: "user-bloqueio-teste",
    lastAccess: "25/05/2026",
    name: "Bloqueio Teste",
    orders: 1,
    phone: "(66) 99123-0000",
    role: "Vendedor",
    status: "blocked",
    statusLabel: "Bloqueado",
    verified: false,
  },
];

const listings: AdminListing[] = [
  {
    city: "Sinop - MT",
    createdAt: "29/05/2026",
    id: "admin-listing-ranger",
    mediaCount: 5,
    price: "R$ 179.900,00",
    seller: "Auto Center Silva",
    status: "published",
    statusLabel: "Publicado",
    title: "Ford Ranger XLT 3.2 4x4",
    type: "Veiculo",
    updatedAt: "Hoje, 08:55",
  },
  {
    city: "Sinop - MT",
    createdAt: "29/05/2026",
    id: "admin-listing-fone",
    mediaCount: 2,
    price: "R$ 3.499,00",
    seller: "Tech Center Sinop",
    status: "review",
    statusLabel: "Revisar midias",
    title: "Smartphone preto 256 GB",
    type: "Produto",
    updatedAt: "Hoje, 08:12",
  },
  {
    city: "Sinop - MT",
    createdAt: "28/05/2026",
    id: "admin-listing-pizza",
    mediaCount: 3,
    price: "R$ 49,90",
    seller: "Hamburgueria Salamanca Ca'dore",
    status: "published",
    statusLabel: "Publicado",
    title: "Pizza grande com entrega",
    type: "Comida",
    updatedAt: "Ontem, 19:30",
  },
  {
    city: "Sorriso - MT",
    createdAt: "27/05/2026",
    id: "admin-listing-beauty",
    mediaCount: 4,
    price: "A partir de R$ 80,00",
    seller: "Studio Thais Lemos",
    status: "review",
    statusLabel: "Aprovar servico",
    title: "Pacote de escova e hidratacao",
    type: "Servico",
    updatedAt: "Ontem, 17:05",
  },
  {
    city: "Sinop - MT",
    createdAt: "26/05/2026",
    id: "admin-listing-house",
    mediaCount: 6,
    price: "R$ 750.000,00",
    seller: "Oliveira Imoveis",
    status: "paused",
    statusLabel: "Pausado",
    title: "Casa a venda - Jardim das Oliveiras",
    type: "Imovel",
    updatedAt: "26/05/2026",
  },
  {
    city: "Lucas do Rio Verde - MT",
    createdAt: "25/05/2026",
    id: "admin-listing-rejected",
    mediaCount: 1,
    price: "R$ 120,00",
    seller: "Conta Bloqueada",
    status: "rejected",
    statusLabel: "Rejeitado",
    title: "Anuncio sem descricao suficiente",
    type: "Produto",
    updatedAt: "25/05/2026",
  },
];

const orders: AdminOrder[] = [
  {
    buyer: "Joao Silva",
    city: "Sinop - MT",
    deliveryWindow: "Hoje, 12:20 - 12:50",
    id: "admin-order-8391",
    itemCount: 3,
    paymentMethod: "Pix",
    placedAt: "Hoje, 08:41",
    seller: "Hamburgueria Salamanca Ca'dore",
    shortId: "#8391",
    status: "on_route",
    statusLabel: "Em rota",
    supportReason: "Entrega em rota atrasada",
    total: "R$ 96,70",
  },
  {
    buyer: "Maria Oliveira",
    city: "Sinop - MT",
    deliveryWindow: "Hoje, 10:40 - 11:10",
    id: "admin-order-8388",
    itemCount: 1,
    paymentMethod: "Carteira SUWAVE",
    placedAt: "Hoje, 08:18",
    seller: "Tech Center Sinop",
    shortId: "#8388",
    status: "paid",
    statusLabel: "Pago",
    total: "R$ 3.499,00",
  },
  {
    buyer: "Lucas Andrade",
    city: "Sorriso - MT",
    deliveryWindow: "Hoje, 15:00 - 16:00",
    id: "admin-order-8379",
    itemCount: 2,
    paymentMethod: "Cartao",
    placedAt: "Hoje, 07:52",
    seller: "Studio Thais Lemos",
    shortId: "#8379",
    status: "preparing",
    statusLabel: "Preparando",
    total: "R$ 180,00",
  },
  {
    buyer: "Ana Costa",
    city: "Sinop - MT",
    deliveryWindow: "Aguardando pagamento",
    id: "admin-order-8371",
    itemCount: 1,
    paymentMethod: "Pix",
    placedAt: "Ontem, 19:46",
    seller: "Oliveira Imoveis",
    shortId: "#8371",
    status: "created",
    statusLabel: "Criado",
    supportReason: "Pix expirando",
    total: "R$ 120,00",
  },
  {
    buyer: "Paulo Mendes",
    city: "Lucas do Rio Verde - MT",
    deliveryWindow: "Entregue ontem, 18:32",
    id: "admin-order-8364",
    itemCount: 4,
    paymentMethod: "Cartao",
    placedAt: "Ontem, 17:10",
    seller: "Mercado Norte",
    shortId: "#8364",
    status: "delivered",
    statusLabel: "Entregue",
    total: "R$ 214,35",
  },
  {
    buyer: "Conta Pendente",
    city: "Sinop - MT",
    deliveryWindow: "Cancelado em 28/05/2026",
    id: "admin-order-8349",
    itemCount: 1,
    paymentMethod: "Pix",
    placedAt: "28/05/2026",
    seller: "Auto Center Silva",
    shortId: "#8349",
    status: "cancelled",
    statusLabel: "Cancelado",
    supportReason: "Solicitacao do comprador",
    total: "R$ 450,00",
  },
  {
    buyer: "Bruna Lima",
    city: "Sinop - MT",
    deliveryWindow: "Reembolso em analise",
    id: "admin-order-8337",
    itemCount: 2,
    paymentMethod: "Carteira SUWAVE",
    placedAt: "27/05/2026",
    seller: "Casa Bella Decor",
    shortId: "#8337",
    status: "refunded",
    statusLabel: "Reembolso",
    supportReason: "Produto indisponivel",
    total: "R$ 389,80",
  },
];

const categories: AdminCategory[] = [
  {
    childrenCount: 6,
    featured: true,
    icon: "FO",
    id: "admin-category-food",
    listingsCount: 128,
    name: "Comidas e mercados",
    parent: "Raiz",
    sortOrder: 1,
    status: "active",
    statusLabel: "Ativa",
    updatedAt: "Hoje, 08:25",
  },
  {
    childrenCount: 8,
    featured: true,
    icon: "VE",
    id: "admin-category-vehicles",
    listingsCount: 72,
    name: "Veiculos",
    parent: "Raiz",
    sortOrder: 2,
    status: "active",
    statusLabel: "Ativa",
    updatedAt: "Hoje, 07:58",
  },
  {
    childrenCount: 5,
    featured: true,
    icon: "IM",
    id: "admin-category-properties",
    listingsCount: 44,
    name: "Imoveis",
    parent: "Raiz",
    sortOrder: 3,
    status: "active",
    statusLabel: "Ativa",
    updatedAt: "Ontem, 18:12",
  },
  {
    childrenCount: 4,
    featured: false,
    icon: "SV",
    id: "admin-category-services",
    listingsCount: 63,
    name: "Servicos locais",
    parent: "Raiz",
    sortOrder: 4,
    status: "review",
    statusLabel: "Revisar icone",
    updatedAt: "Ontem, 16:40",
  },
  {
    childrenCount: 3,
    featured: false,
    icon: "EV",
    id: "admin-category-events",
    listingsCount: 19,
    name: "Eventos",
    parent: "Raiz",
    sortOrder: 5,
    status: "active",
    statusLabel: "Ativa",
    updatedAt: "27/05/2026",
  },
  {
    childrenCount: 2,
    featured: false,
    icon: "CL",
    id: "admin-category-legacy",
    listingsCount: 0,
    name: "Classificados antigos",
    parent: "Raiz",
    sortOrder: 99,
    status: "hidden",
    statusLabel: "Oculta",
    updatedAt: "26/05/2026",
  },
];

const financeItems: AdminFinanceItem[] = [
  {
    amount: "R$ 84,70",
    city: "Sinop - MT",
    createdAt: "Hoje, 08:13",
    id: "admin-finance-saque-maria",
    method: "Pix",
    owner: "Maria Oliveira",
    reason: "Saque afiliado",
    status: "pending",
    statusLabel: "Validar saque",
    type: "Afiliados",
  },
  {
    amount: "R$ 1.248,90",
    city: "Sinop - MT",
    createdAt: "Hoje, 07:44",
    id: "admin-finance-repasse-salamanca",
    method: "Carteira SUWAVE",
    owner: "Hamburgueria Salamanca Ca'dore",
    reason: "Repasse de vendas",
    status: "approved",
    statusLabel: "Aprovado",
    type: "Repasse",
  },
  {
    amount: "R$ 36,20",
    city: "Sorriso - MT",
    createdAt: "Ontem, 18:02",
    id: "admin-finance-cashback-lucas",
    method: "Carteira",
    owner: "Lucas Andrade",
    reason: "Cashback promocional",
    status: "paid",
    statusLabel: "Pago",
    type: "Cashback",
  },
  {
    amount: "R$ 450,00",
    city: "Sinop - MT",
    createdAt: "Ontem, 16:35",
    id: "admin-finance-estorno-conta",
    method: "Pix",
    owner: "Conta Pendente",
    reason: "Estorno pedido #8349",
    status: "pending",
    statusLabel: "Aguardando analise",
    type: "Estorno",
  },
  {
    amount: "R$ 2.980,00",
    city: "Lucas do Rio Verde - MT",
    createdAt: "27/05/2026",
    id: "admin-finance-bloqueio-auto",
    method: "Transferencia",
    owner: "Auto Center Silva",
    reason: "Divergencia documental",
    status: "blocked",
    statusLabel: "Bloqueado",
    type: "Repasse",
  },
];

const moderationItems: AdminModerationItem[] = [
  {
    age: "12 min",
    area: "Anuncios",
    id: "admin-moderation-fone",
    owner: "Tech Center Sinop",
    priority: "alta",
    reason: "Imagem com baixa nitidez",
    status: "queued",
    statusLabel: "Na fila",
    title: "Smartphone preto 256 GB",
  },
  {
    age: "28 min",
    area: "Eventos",
    id: "admin-moderation-workshop",
    owner: "Studio Thais Lemos",
    priority: "media",
    reason: "Evento privado aguardando comprovante",
    status: "reviewing",
    statusLabel: "Em revisao",
    title: "Workshop privado de beleza",
  },
  {
    age: "1 h",
    area: "Denuncias",
    id: "admin-moderation-comment",
    owner: "Joao Silva",
    priority: "alta",
    reason: "Comentario denunciado por linguagem ofensiva",
    status: "queued",
    statusLabel: "Na fila",
    title: "Avaliacao de pedido #8391",
  },
  {
    age: "2 h",
    area: "Servicos",
    id: "admin-moderation-builder",
    owner: "Norte Construcoes",
    priority: "baixa",
    reason: "Perfil atualizado com nova galeria",
    status: "approved",
    statusLabel: "Aprovado",
    title: "Servico de construcao",
  },
  {
    age: "Ontem",
    area: "Produtos",
    id: "admin-moderation-rejected",
    owner: "Conta Bloqueada",
    priority: "media",
    reason: "Descricao insuficiente",
    status: "rejected",
    statusLabel: "Rejeitado",
    title: "Anuncio sem descricao suficiente",
  },
];

export function getAdminDashboard() {
  return dashboard;
}

export function getAdminUsers() {
  return users;
}

export function getAdminListings() {
  return listings;
}

export function getAdminOrders() {
  return orders;
}

export function getAdminCategories() {
  return categories;
}

export function getAdminFinanceItems() {
  return financeItems;
}

export function getAdminModerationItems() {
  return moderationItems;
}
